services:
  giropops-senhas:
    image: giropops-senhas:1.0
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
       REDIS_HOST: redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - giropops

networks:
  giropops:
    driver: bridge